package io.github.yozedens.secureauth.security.keystore

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import io.github.yozedens.secureauth.core.crypto.AeadCipher
import io.github.yozedens.secureauth.core.crypto.KeyUnavailableException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM with a non-exportable Android Keystore key (design §24, ADR 0001).
 *
 * - The IV is generated by Keystore; callers cannot supply one.
 * - The key does not require user authentication (ADR 0001 §1).
 * - StrongBox is preferred, with fallback when the device has none.
 */
class KeystoreAeadCipher(private val alias: String = MASTER_KEY_ALIAS) : AeadCipher {

    override fun encrypt(plaintext: ByteArray, aad: ByteArray): AeadCipher.Sealed {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        initOrUnavailable { cipher.init(Cipher.ENCRYPT_MODE, key()) }
        cipher.updateAAD(aad)
        val ciphertext = cipher.doFinal(plaintext)
        return AeadCipher.Sealed(cipher.iv, ciphertext)
    }

    override fun decrypt(iv: ByteArray, ciphertext: ByteArray, aad: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        initOrUnavailable { cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv)) }
        cipher.updateAAD(aad)
        return cipher.doFinal(ciphertext)
    }

    fun keyExists(): Boolean = keyStore().containsAlias(alias)

    /**
     * Creates the key if it does not exist yet. Only called from first-time initialization;
     * an existing key is never replaced or deleted (ADR 0001 §3).
     *
     * @return true if StrongBox backs the new key; null if the key already existed.
     */
    fun createKeyIfAbsent(): Boolean? {
        if (keyExists()) return null
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
                generate(strongBox = true)
                return true
            } catch (ignored: StrongBoxUnavailableException) {
                // No StrongBox on this device: fall back to the regular Keystore below.
            }
        }
        generate(strongBox = false)
        return false
    }

    private fun generate(strongBox: Boolean) {
        val spec = KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_BITS)
            .apply { if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) setIsStrongBoxBacked(true) }
            .build()
        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).run {
            init(spec)
            generateKey()
        }
    }

    private fun key(): SecretKey =
        keyStore().getKey(alias, null) as? SecretKey ?: throw KeyUnavailableException("vault key missing")

    private fun keyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private inline fun initOrUnavailable(init: () -> Unit) {
        try {
            init()
        } catch (e: KeyPermanentlyInvalidatedException) {
            throw KeyUnavailableException("vault key invalidated", e)
        }
    }

    companion object {
        const val MASTER_KEY_ALIAS = "secureauth_master_key_v1"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val KEY_BITS = 256
        private const val TAG_BITS = 128
    }
}
